name: dicom_web
description: A library for reading and writing DICOM files and DICOM JSONs.
version: 0.1.0
topics:
  - dicom
  - medical
  - web
  - json

environment:
  sdk: ^3.3.1

# Add regular dependencies here.
dependencies:
  collection: ^1.18.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
